name: CI
on:
    push:
        branches: [ main ]
jobs:     
    deploy:
        runs-on: self-hosted
        environment: Dev
        strategy: 
          matrix:
            node-version: [16.x]
            
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node-version }}
            env:
              PORT: ${{ secrets.PORT }}
              SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
              JWT_SECRET: ${{ secrets.JWT_SECRET }}
              MONGODB_URL: ${{ secrets.MONGODB_URL }}
          - run: echo "${{ secrets.PORT }}"
          - run: npm install
          - run: npm run start --if-present
          - run: npm test
            
