name: CI
on:
    push:
        branches: [ main ]
jobs:     
    deploy:
        runs-on: self-hosted
        environment: Dev
        strategy: 
          matrix:
            node-version: [16.x]
            
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node-version }}
            
          #- run: echo "${{ secrets.PORT }}"
          - run: npm install
          - run: |
              mkdir config
              touch config/dev.env
              echo PORT: ${{ secrets.PORT }} >> config/dev.env
              echo SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }} >> config/dev.env
              echo JWT_SECRET: ${{ secrets.JWT_SECRET }} >> config/dev.env
              echo MONGODB_URL: ${{ secrets.MONGODB_URL }} >> config/dev.env 
          - run: |
              cat config/dev.env
          - run: npm run start --if-present

          #  env:
          #    PORT: ${{ secrets.PORT }}
          #    SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          #    JWT_SECRET: ${{ secrets.JWT_SECRET }}
          #    MONGODB_URL: ${{ secrets.MONGODB_URL }}
          # - run: npm test
            
