#workflow name
name: 'test run'

#event, trigger action that running our Jobs.
#In this file we trigger pm2-configuration every we push code to repository.
on: [push]
jobs:
  test:
    #runner, This job will be running in runner with Ubuntu Server latest version.
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3 #checkout code from repository, so we code downloaded in runner.
      - uses: actions/setup-node@v3 #setup nodejs in our runner
      - run: npm install
      - run: |
          mkdir config
          touch config/test.env
          echo PORT: ${{ secrets.PORT }} >> config/test.env
          echo SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }} >> config/test.env
          echo JWT_SECRET: ${{ secrets.JWT_SECRET }} >> config/test.env
          echo MONGODB_URL: ${{ secrets.MONGODB_URL }} >> config/test.env
      - run: |
          cat config/test.env
      - run: npm run action-test
