#workflow name
name: 'test run'

#event, trigger action that running our Jobs.
#In this file we trigger pm2-configuration every we push code to repository.
on: [push]
jobs:
  build-and-test:
    name: 'Build and Test'
    runs-on: self-hosted
    permissions:
      contents: read
      checks: write
      id-token: write

    steps:
      - uses: actions/checkout@v3 #checkout code from repository, so we code downloaded in runner.
      - uses: actions/setup-node@v3 #setup nodejs in our runner
      - run: npm install
      - run: |
          mkdir config
          touch config/test.env
          echo PORT=${{ secrets.PORT }} >> config/test.env
          echo SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} >> config/test.env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> config/test.env
          echo MONGODB_URL=${{ secrets.MONGODB_URL }} >> config/test.env
      - run: |
          cat config/test.env
      - run: npm run action-test
      # - name: Create test summary
      #   uses: test-summary/action@dist
      #   with:
      #     paths: test-results/**/*.xml
      #   if: always()
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: 'test-results/**/*.xml'
          include_passed: true

  # publish-test-results:
  #   name: 'Publish Tests Results'
  #   needs: build-and-test
  #   runs-on: self-hosted
  #   # the build-and-test job might be skipped, we don't need to run this job then
  #   if: success() || failure()

  #   steps:
  #     - name: Download Artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         path: artifacts

  #     - name: Publish Test Results
  #       uses: EnricoMi/publish-unit-test-result-action/composite@v2
  #       with:
  #         files: 'artifacts/**/*.xml'
